### ISSUE TITLE
Is it possible to update this application to of10 or the latest version?

### ISSUE THREAD

**Issue by scramjetFoam** [ZSHtju/CRPWA#1]
Hi Zhong,

I accidentally found this very useful postProcess application. But unfortunately this version is rather old. 
I tried to adapt it to of10 myself, but it was too challenging for me. 
I was wondering if you have any plans to update this program.

Regards,
Shang

**Comment by ZSHtju** [comment]
> Hi Zhong,
> 
> I accidentally found this very useful postProcess application. But unfortunately this version is rather old. I tried to adapt it to of10 myself, but it was too challenging for me. I was wondering if you have any plans to update this program.
> 
> Regards, Shang

Hi Shang,
Currently, I don't have a plan to update this code to OpenFOAM10.
BR

**Comment by scramjetFoam** [comment]
Roger that, and thanks for sharing this useful code.

Best regards,
Shang
